// Mutable global runtime parameters.
const globalParams = {
  gravity:  9.81,
  springK:  50,
  springC:  1.0,
  softHz:   3.0,
  softZeta: 0.7,
  distCompliance: 0.0,
  baumgarte:      0.2,
  siIters:        4,
  posIters:       2,
  linDamp:        0.5,
  angDamp:        0.5,
  restitution:    0.2,
  col3Alpha:      0.0,
  col3PosIters:   2,
  col3VelIters:   4,
  col3Mus:        0.5,
  col3Mud:        0.3,
  col3N:          400,
  col4Mus:        0.6,
  col4Mud:        0.4,
  col4N:          250,
  col4Ramp:       25,
};
